spring.application.name=devportal
server.port=${SERVER_PORT}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.auto-index-creation=true