spring.application.name=devportal
server.port=8000

spring.data.mongodb.uri=mongodb+srv://sampannapiya13_db_user:NLWTXQTBrmOJZlOu@clusterfonepaydevportal.lsbne7g.mongodb.net/fonepay-dev-portal?appName=ClusterFonepayDevPortal
spring.data.mongodb.database=fonepay-dev-portal
spring.data.mongodb.auto-index-creation=true